apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # 'password' base64
  mysql-user: YWRtaW4=              # 'admin'
  mysql-password: cGFzc3dvcmQ=      # 'password'
